# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

name: Dependabot Matrix Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [dependabot/**]

jobs:
  notify:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Matrix
        run: echo "Dependabot made a change in the repository!"

